### ISSUE TITLE
直线行驶

### ISSUE THREAD

**Issue by maybe-raven** [CCDSY/PhotonBox-2016#10]
1. 安装三轴加速度仪
2. 代码
3. 真机测试

**Comment by Smigus** [comment]
三轴陀螺仪安装信息：
- x轴朝前，y轴朝右，z轴朝下
- 若机器人顺时针旋转，则z轴陀螺仪读数为正

**Comment by Smigus** [comment]
代码：
- 将陀螺仪的角速度数据对时间累加获得角度（顺时针旋转为正）。角度大于零就转左，角度小于零就转右。

**Comment by maybe-raven** [comment]
于[#43](https://github.com/CCDSY/PhotonBox-2016/pull/43)解决。
