### ISSUE TITLE
锁定爬升机构的伺服电机

### ISSUE THREAD

**Issue by Smigus** [CCDSY/PhotonBox-2016#33]
测试时的代码意思如下：
- 初始化`Climber`时，伺服电机被设定到锁定位置。
- 点击SmartDashboard上的Unlock Climber时，伺服电机被设定到解锁位置`ClimberConfig.lockServoUnlockPosition`.
- 点击SmartDashboard上的Reset Climber Lock时，伺服电机被设定到锁定位置`ClimberConfig.lockServoLockPosition`.

伺服电机出现了如下问题：
- 每次初始化`Climber`时，伺服电机被设定到解锁位置
- 点击SmartDashboard上的Unlock Climber时，伺服电机被设定到锁定位置。
- 点击SmartDashboard上的Reset Climber Lock时，伺服电机被设定到解锁位置。
  我尝试了调换`ClimberConfig.lockServoLockPosition`（锁定位置）和`ClimberConfig.lockServoUnlockPosition`（解锁位置）的值，然而结果毫无变化。

**Comment by maybe-raven** [comment]
Fixed.
