### ISSUE TITLE
射球机构上方挡板

### ISSUE THREAD

**Issue by Smigus** [CCDSY/PhotonBox-2016#52]
射球机构上方挡板急需加固。它今天测试射球的时候掉了两次。

**Comment by Smigus** [comment]
挡板用扎带扎住了。重复之前让挡板掉下来的动作，挡板没有再掉下来。
另外在导轨前端贴了胶布，吸球没有再被导轨卡住。

**Comment by maybe-raven** [comment]
所以你这算是解决了吗？
