### ISSUE TITLE
机器人拐弯

### ISSUE THREAD

**Issue by Smigus** [CCDSY/PhotonBox-2016#54]
根据目前`DriveTrain`的代码，机器人从静止状态开始拐弯时（不给机器人任何前进／后退值）会发生明显且快速的前进／后退运动。

**Comment by maybe-raven** [comment]
Solved in commit [f3e4c7b](https://github.com/CCDSY/PhotonBox-2016/commit/f3e4c7b29345aec9db38fb1afe87acd8d334ac3c)
