### ISSUE TITLE
交互模式改进

### ISSUE THREAD

**Issue by maybe-raven** [CCDSY/PhotonBox-2016#57]
# 底盘
### 添加开关来启用或关闭gyro辅助驾驶。

gyro辅助驾驶会导致较明显的速度降低，过部分障碍物时关闭gyro辅助驾驶会容易很多。
值得整理一下代码。将gyro辅助功能的实现放进[DriveTrain](https://github.com/CCDSY/PhotonBox-2016/blob/master/src/org/usfirst/frc/team6179/robot/subsystems/DriveTrain.java)里，[调用它的command](https://github.com/CCDSY/PhotonBox-2016/blob/master/src/org/usfirst/frc/team6179/robot/commands/drivetrain/ArcadeDriveWithJoystick.java)只负责从joystick读input并喂给DriveTrain，另外有一个command负责切换状态（就像[AimMode](https://github.com/CCDSY/PhotonBox-2016/blob/master/src/org/usfirst/frc/team6179/robot/commands/AimMode.java)一样）。
### 将前进后退和旋转分到2个摇杆上

左摇杆Y前进后退，右摇杆X旋转。
# 射球机构
### 送球伺服电机复位

收球和射球前后都应该发送信号将私服调到合适位置。
目前收球时会因为球进来得太猛而将私服撞到一个不太正确的位置，但是为了保证收球动作的有效性，又不能调低收球电机的转速。
### 送球伺服电机重新定位

也许它现在是可以的，要看看。
### 添加可以快速进行定位测试的支持

现在的情况是送球伺服的位置经常会变，所以要支持快速地进行测试。（可能作为一个command）
# 抬升机构
### 添加操作支持

到现在都还不能用手柄来收紧或释放绞盘电机。怎么能这样。
# SmartDashboard
### 移除不需要的command
1. Shoot
2. Collect
3. Send video (the one without crosshair)
4. Climber lock control
   ### 添加某些command的控制
5. Lock and unlock climber
6. Maybe just send the video automatically?

**Comment by Smigus** [comment]
我好像忘了在之前两个Commit里饮用这个issue了。。。
其实是把底盘部分按要求改了。
